import { contracts } from "./harness";

const job = {
	id: "job-1",
	scope: "local",
	kind: "dialogue.run",
	subjectRef: null,
	parentJobId: null,
	lane: "interactive",
	state: "queued",
	attempt: 0,
	maxAttempts: 3,
	waitReason: null,
	errorCode: null,
	availableAt: "2026-10-10T00:00:00.000Z",
	deadlineAt: null,
	cancelRequestedAt: null,
	createdAt: "2026-10-10T00:00:00.000Z",
	updatedAt: "2026-10-10T00:00:00.000Z",
	finishedAt: null,
	revision: 1,
};
const attempt = {
	jobId: "job-1",
	attempt: 1,
	startedAt: "2026-10-10T00:00:00.000Z",
	endedAt: null,
	outcome: null,
	errorCode: null,
};
contracts("queue client", [
	{
		name: "queueStatus",
		call: (c) => c.queueStatus(),
		method: "GET",
		path: "/api/queue/status",
		response: {
			lanes: {
				interactive: { queued: 1, running: 0, failed: 0, oldestWaitMs: null },
			},
			resources: { larm: { inUse: 0, capacity: 1 } },
			openJobs: 1,
			lastScanAt: null,
		},
	},
	{
		name: "jobs",
		call: (c) => c.jobs({ state: "queued", limit: 5 }),
		method: "GET",
		path: "/api/jobs?state=queued&limit=5",
		response: { items: [job], nextCursor: null },
	},
	{
		name: "job",
		call: (c) => c.job("job/1"),
		method: "GET",
		path: "/api/jobs/job%2F1",
		response: job,
	},
	{
		name: "jobAttempts",
		call: (c) => c.jobAttempts("job-1"),
		method: "GET",
		path: "/api/jobs/job-1/attempts",
		response: [attempt],
	},
	{
		name: "cancelJob",
		call: (c) => c.cancelJob("job-1", "user"),
		method: "POST",
		path: "/api/jobs/job-1/cancel",
		body: { reason: "user" },
		response: { ...job, state: "cancel_requested" },
	},
]);

const schedule = {
	id: "sch-1",
	requestId: "11111111-1111-4111-8111-111111111111",
	scope: "local",
	targetKind: "dialogue.prompt",
	targetVersion: 1,
	targetPayload: { text: "hi" },
	state: "active",
	revision: 1,
	mode: "once",
	anchorAt: "2026-10-11T00:00:00.000Z",
	intervalMs: null,
	nextDueAt: "2026-10-11T00:00:00.000Z",
	misfirePolicy: "coalesce",
	graceMs: 300000,
	overlapPolicy: "skip",
	deferReason: null,
	createdAt: "2026-10-10T00:00:00.000Z",
	updatedAt: "2026-10-10T00:00:00.000Z",
};
const occurrence = {
	id: "occ-1",
	scheduleId: "sch-1",
	scheduleRevision: 1,
	scheduledAt: "2026-10-11T00:00:00.000Z",
	state: "dispatched",
	jobId: "job-1",
	subjectRef: null,
	jobState: "queued",
	reason: null,
	createdAt: "2026-10-11T00:00:00.000Z",
};
contracts("scheduler client", [
	{
		name: "createSchedule",
		call: (c) =>
			c.createSchedule({
				requestId: schedule.requestId,
				target: { kind: "dialogue.prompt", payload: { text: "hi" } },
				schedule: { type: "once", at: "2026-10-11T00:00:00.000Z" },
			}),
		method: "POST",
		path: "/api/schedules",
		body: {
			requestId: schedule.requestId,
			target: { kind: "dialogue.prompt", payload: { text: "hi" } },
			schedule: { type: "once", at: "2026-10-11T00:00:00.000Z" },
		},
		response: schedule,
	},
	{
		name: "schedules",
		call: (c) => c.schedules({ state: "active" }),
		method: "GET",
		path: "/api/schedules?state=active",
		response: { items: [schedule], nextCursor: null },
	},
	{
		name: "schedule",
		call: (c) => c.schedule("sch-1"),
		method: "GET",
		path: "/api/schedules/sch-1",
		response: schedule,
	},
	{
		name: "scheduleOccurrences",
		call: (c) => c.scheduleOccurrences("sch-1", { limit: 2 }),
		method: "GET",
		path: "/api/schedules/sch-1/occurrences?limit=2",
		response: { items: [occurrence], nextCursor: null },
	},
	{
		name: "pauseSchedule",
		call: (c) => c.pauseSchedule("sch-1", 1),
		method: "POST",
		path: "/api/schedules/sch-1/pause",
		body: { expectedRevision: 1 },
		response: { ...schedule, state: "paused", revision: 2 },
	},
	{
		name: "resumeSchedule",
		call: (c) => c.resumeSchedule("sch-1", 2),
		method: "POST",
		path: "/api/schedules/sch-1/resume",
		body: { expectedRevision: 2 },
		response: schedule,
	},
	{
		name: "cancelSchedule",
		call: (c) => c.cancelSchedule("sch-1", 1),
		method: "POST",
		path: "/api/schedules/sch-1/cancel",
		body: { expectedRevision: 1 },
		response: { ...schedule, state: "cancelled", revision: 2 },
	},
]);
