import { spawn } from "node:child_process";
import { existsSync, mkdirSync, readdirSync } from "node:fs";
import { join } from "node:path";
import { randomUUID } from "node:crypto";
import {
	executionSpecSchema,
	storedSpecSchema,
	legacyProtocolVersion,
	protocolVersion,
	receiptSchema,
	eventSchema,
	id,
	type StoredSpec,
	type ExecutionReceipt,
} from "./contracts";
import { loadConfig, validateExecutable, type RunnerConfig } from "./config";
import {
	atomicWrite,
	canonical,
	digest,
	lock,
	optionalJson,
	privateDirectory,
	readPrivate,
	runPath,
	totalSize,
} from "./storage";
import { assertContinuable } from "./continuation";
import { initialObservation } from "./observation";
import { workspace } from "./workspace";

export function prepareSpool(config: RunnerConfig) {
	privateDirectory(config.spoolRoot);
	for (const name of ["runs", "specs", "operations", "workspaces"])
		privateDirectory(join(config.spoolRoot, name));
}
export function publishSpec(
	config: RunnerConfig,
	specRef: string,
	spec: StoredSpec,
) {
	prepareSpool(config);
	storedSpecSchema.parse(spec);
	// Spec references are UUIDs generated by the backend, never a model-supplied file path.
	if (!/^[a-zA-Z0-9][a-zA-Z0-9_-]{0,99}$/.test(specRef))
		throw new Error("runner_invalid_spec_ref");
	const release = lock(join(config.spoolRoot, "specs.lock"));
	try {
		const path = join(config.spoolRoot, "specs", `${specRef}.json`);
		const previous = optionalJson<StoredSpec>(path);
		if (previous && canonical(previous) !== canonical(spec))
			throw new Error("runner_operation_conflict");
		if (!previous) atomicWrite(path, spec);
	} finally {
		release();
	}
}
export function readReceipt(
	config: RunnerConfig,
	executionId: string,
): ExecutionReceipt {
	const path = runPath(config.spoolRoot, executionId);
	const saved = receiptSchema.parse(
		JSON.parse(readPrivate(join(path, "receipt.json"))),
	);
	// A stale active receipt does not prove a process is dead. Never replay or kill a saved PID.
	const leaseMs =
		config.mode === "fixture"
			? (config.fixtureLimits?.leaseMs ?? 120000)
			: 120000;
	if (
		["reserved", "running", "stopping"].includes(saved.state) &&
		Date.now() - saved.updatedAt > leaseMs + 10000
	)
		return {
			...saved,
			state: "outcome_unknown",
			reason: "worker_receipt_stale",
			childrenStopped: false,
		};
	return saved;
}
export function createRunner(configPath: string, fixtureAllowed = false) {
	const config = loadConfig(configPath, fixtureAllowed);
	prepareSpool(config);
	function probe(workspaceId: string) {
		workspace(config, workspaceId);
		validateExecutable(config);
		// Codex's workspace-write sandbox alone does not protect unrelated host reads/auth/network.
		// Until a verified isolation launcher is supplied, production execution is fail-closed.
		if (config.mode === "production")
			return {
				version: protocolVersion,
				adapter: "codex-exec" as const,
				cliVersion: null,
				available: false,
				reason: "isolation_not_verified",
				capabilities: [],
			};
		return {
			version: protocolVersion,
			adapter: "codex-exec" as const,
			cliVersion: "fixture",
			available: true,
			reason: null,
			capabilities: [
				"jsonl",
				"explicit-resume",
				"process-group",
				"durable-receipts",
			],
		};
	}
	return {
		config,
		async probe(workspaceId: string) {
			return probe(workspaceId);
		},
		async start(
			specRef: string,
			operationId: string,
			executionId: string,
			continuation: boolean,
		) {
			id.parse(specRef);
			id.parse(operationId);
			id.parse(executionId);
			const stored = storedSpecSchema.parse(
				JSON.parse(
					readPrivate(join(config.spoolRoot, "specs", `${specRef}.json`)),
				),
			);
			// An old-protocol spec may be read for reconciliation but never starts new work.
			if (stored.version === legacyProtocolVersion)
				throw new Error("runner_protocol_mismatch");
			const spec = executionSpecSchema.parse(stored);
			if (
				spec.operationId !== operationId ||
				spec.executionId !== executionId ||
				continuation !== (spec.kind === "continue")
			)
				throw new Error("runner_spec_mismatch");
			const release = lock(join(config.spoolRoot, "operations.lock"));
			try {
				const operationPath = join(
					config.spoolRoot,
					"operations",
					`${operationId}.json`,
				);
				const prior = optionalJson<{ executionId: string; digest: string }>(
					operationPath,
				);
				if (prior) {
					if (
						prior.executionId !== executionId ||
						prior.digest !== digest(canonical(spec))
					)
						throw new Error("runner_operation_conflict");
					return readReceipt(config, executionId);
				}
				if (spec.deadlineAt <= Date.now())
					throw new Error("runner_authority_expired");
				if (!probe(spec.workspaceId).available)
					throw new Error("runner_isolation_unavailable");
				if (continuation) {
					if (!spec.previousExecutionId || !spec.sessionId)
						throw new Error("runner_session_required");
					assertContinuable(
						config,
						spec,
						readReceipt(config, spec.previousExecutionId),
					);
				} else if (spec.sessionId !== null || spec.previousExecutionId !== null)
					throw new Error("runner_session_invalid");
				if (
					readdirSync(join(config.spoolRoot, "runs")).length >= 1000 ||
					totalSize(config.spoolRoot) > 190 * 1024 * 1024
				)
					throw new Error("runner_storage_full");
				const reservation = join(
					config.spoolRoot,
					"workspaces",
					`${spec.workspaceId}.json`,
				);
				if (
					existsSync(
						join(
							config.spoolRoot,
							"workspaces",
							`${spec.workspaceId}.git.json`,
						),
					)
				)
					throw new Error("runner_workspace_busy");
				const held = optionalJson<{ executionId: string }>(reservation);
				if (continuation && held?.executionId !== spec.previousExecutionId)
					throw new Error("runner_session_busy_or_stale");
				if (held) {
					const old = readReceipt(config, held.executionId);
					if (
						!old.childrenStopped ||
						!["exited", "stopped"].includes(old.state)
					)
						throw new Error("runner_workspace_busy");
				}
				const path = runPath(config.spoolRoot, executionId);
				mkdirSync(path, { mode: 0o700 });
				const receipt: ExecutionReceipt = {
					executionId,
					operationId,
					specDigest: digest(canonical(spec)),
					generation: spec.generation,
					state: "reserved",
					sessionId: spec.sessionId,
					seq: 0,
					// Unknown until the owning worker proves a spawn (true) or a stop before it (false).
					observation: {
						...initialObservation(),
						processStarted: "unknown",
					},
					turnFinished: false,
					childrenStopped: false,
					evidenceComplete: true,
					reason: null,
					exitCode: null,
					updatedAt: Date.now(),
				};
				atomicWrite(join(path, "spec.json"), spec);
				// A worker uses the configuration authorized at reservation, never a later edit.
				atomicWrite(join(path, "runner-config.json"), config);
				const sessionHomeId = spec.previousExecutionId
					? id.parse(
							JSON.parse(
								readPrivate(
									join(
										runPath(config.spoolRoot, spec.previousExecutionId),
										"session-home.json",
									),
								),
							).executionId,
						)
					: executionId;
				atomicWrite(join(path, "session-home.json"), {
					executionId: sessionHomeId,
				});
				atomicWrite(join(path, "identity.json"), { nonce: randomUUID() });
				atomicWrite(join(path, "receipt.json"), receipt);
				atomicWrite(join(path, "lease.json"), {
					expiresAt: Date.now() + (config.fixtureLimits?.leaseMs ?? 120000),
				});
				atomicWrite(reservation, { executionId });
				// The durable intent precedes spawn. A crash from here is unknown, never an automatic restart.
				atomicWrite(operationPath, { executionId, digest: receipt.specDigest });
				atomicWrite(join(path, "spawn-intent.json"), {
					requestedAt: Date.now(),
				});
				const worker = spawn(
					process.execPath,
					[
						join(import.meta.dir, "worker.ts"),
						join(path, "runner-config.json"),
						executionId,
						...(fixtureAllowed ? ["--fixture"] : []),
					],
					{
						detached: true,
						stdio: "ignore",
						env: { PATH: "/usr/bin:/bin", LANG: "en_US.UTF-8" },
					},
				);
				worker.on("error", () => {
					/* intent is retained; inspect reports unknown, no replay */
				});
				worker.unref();
				return receipt;
			} finally {
				release();
			}
		},
		inspect(
			executionId: string,
			afterSeq: number,
			limit: number,
			renewLease: boolean,
		) {
			if (
				!Number.isSafeInteger(afterSeq) ||
				afterSeq < 0 ||
				!Number.isSafeInteger(limit) ||
				limit < 1 ||
				limit > 100
			)
				throw new Error("runner_invalid_cursor");
			const path = runPath(config.spoolRoot, executionId);
			const receipt = readReceipt(config, executionId);
			if (afterSeq > receipt.seq) throw new Error("runner_invalid_cursor");
			if (
				renewLease &&
				["reserved", "running"].includes(receipt.state) &&
				!existsSync(join(path, "stop.json"))
			)
				atomicWrite(join(path, "lease.json"), {
					expiresAt: Date.now() + (config.fixtureLimits?.leaseMs ?? 120000),
				});
			const events = [];
			let bytes = 0;
			// One immutable metadata file per event avoids adopting a partially appended JSONL tail.
			for (
				let seq = afterSeq + 1;
				seq <= receipt.seq && events.length < limit;
				seq++
			) {
				const event = eventSchema.parse(
					JSON.parse(readPrivate(join(path, "events", `${seq}.json`))),
				);
				bytes += Buffer.byteLength(canonical(event));
				if (bytes > 256 * 1024) break;
				events.push(event);
			}
			const nextCursor = events.at(-1)?.seq ?? afterSeq;
			return {
				receipt,
				events,
				nextCursor,
				hasMore: nextCursor < receipt.seq,
				observedAt: Date.now(),
			};
		},
		stop(
			executionId: string,
			generation: number,
			operationId: string,
			reason: string,
		) {
			id.parse(operationId);
			if (
				!Number.isSafeInteger(generation) ||
				generation < 1 ||
				!["cancel", "pause", "authority_revoked", "shutdown"].includes(reason)
			)
				throw new Error("runner_invalid_stop");
			const operationLock = lock(join(config.spoolRoot, "operations.lock"));
			try {
				const commandPath = join(
					config.spoolRoot,
					"operations",
					`stop-${operationId}.json`,
				);
				const command = { executionId, generation, reason };
				const oldCommand = optionalJson<typeof command>(commandPath);
				if (oldCommand && canonical(oldCommand) !== canonical(command))
					throw new Error("runner_operation_conflict");
				if (!existsSync(runPath(config.spoolRoot, executionId))) {
					const specs = readdirSync(join(config.spoolRoot, "specs"))
						.filter((n) => n.endsWith(".json") && !n.startsWith("git-"))
						.map((n) =>
							storedSpecSchema.parse(
								JSON.parse(readPrivate(join(config.spoolRoot, "specs", n))),
							),
						);
					const spec = specs.find((s) => s.executionId === executionId);
					if (!spec || spec.generation !== generation)
						throw new Error("runner_intent_not_found");
					const operationPath = join(
						config.spoolRoot,
						"operations",
						`${spec.operationId}.json`,
					);
					if (existsSync(operationPath))
						throw new Error("runner_operation_unknown");
					const path = runPath(config.spoolRoot, executionId);
					mkdirSync(path, { mode: 0o700 });
					const receipt: ExecutionReceipt = {
						executionId,
						operationId: spec.operationId,
						specDigest: digest(canonical(spec)),
						generation,
						state: "stopped",
						sessionId: spec.sessionId,
						seq: 0,
						// Stopped before the owning worker could spawn: the CLI never existed.
						observation: {
							...initialObservation(),
							processStarted: false,
						},
						turnFinished: false,
						childrenStopped: true,
						evidenceComplete: true,
						reason: "stopped_before_spawn",
						exitCode: null,
						updatedAt: Date.now(),
					};
					atomicWrite(join(path, "spec.json"), spec);
					atomicWrite(join(path, "receipt.json"), receipt);
					atomicWrite(join(path, "stop.json"), { operationId, reason });
					atomicWrite(commandPath, command);
					atomicWrite(operationPath, {
						executionId,
						digest: receipt.specDigest,
					});
					return receipt;
				}
				const receipt = readReceipt(config, executionId);
				if (receipt.generation !== generation)
					throw new Error("runner_generation_conflict");
				const path = runPath(config.spoolRoot, executionId);
				const release = lock(join(path, "control.lock"));
				try {
					const prior = optionalJson<{ operationId: string; reason: string }>(
						join(path, "stop.json"),
					);
					if (
						prior &&
						prior.operationId === operationId &&
						prior.reason !== reason
					)
						throw new Error("runner_operation_conflict");
					// Revocation is irreversible. A later pause cannot weaken cancel/shutdown.
					if (!prior || (prior.reason === "pause" && reason !== "pause"))
						atomicWrite(join(path, "stop.json"), { operationId, reason });
					if (!oldCommand) atomicWrite(commandPath, command);
					// No OS signal from a recovered saved PID. The owning worker observes this request.
					return ["exited", "stopped", "outcome_unknown"].includes(
						receipt.state,
					)
						? receipt
						: { ...receipt, state: "stopping" as const };
				} finally {
					release();
				}
			} finally {
				operationLock();
			}
		},
		readEvidence(
			executionId: string,
			evidenceRef: string,
			offset: number,
			limit: number,
		) {
			if (
				!Number.isSafeInteger(offset) ||
				offset < 0 ||
				!Number.isSafeInteger(limit) ||
				limit < 4 ||
				limit > 65536
			)
				throw new Error("runner_invalid_range");
			const path = runPath(config.spoolRoot, executionId);
			const receipt = readReceipt(config, executionId);
			let found: string | null = null;
			for (let seq = 1; seq <= receipt.seq; seq++) {
				const event = eventSchema.parse(
					JSON.parse(readPrivate(join(path, "events", `${seq}.json`))),
				);
				if (event.payloadRef === evidenceRef) {
					found = event.payloadDigest;
					break;
				}
			}
			if (!found) throw new Error("runner_evidence_not_registered");
			const data = Buffer.from(
				readPrivate(join(path, "evidence", `${evidenceRef}.txt`)),
			);
			if (offset > data.length) throw new Error("runner_invalid_range");
			if (digest(data) !== found)
				throw new Error("runner_evidence_digest_conflict");
			if (offset < data.length && (data[offset]! & 0xc0) === 0x80)
				throw new Error("runner_invalid_range");
			let end = Math.min(offset + limit, data.length);
			while (end < data.length && (data[end]! & 0xc0) === 0x80) end--;
			return {
				text: new TextDecoder("utf-8", { fatal: true, ignoreBOM: true }).decode(
					data.subarray(offset, end),
				),
				digest: digest(data),
				totalBytes: data.length,
				truncated: offset !== 0 || end < data.length,
				nextOffset: end,
			};
		},
	};
}
